### ISSUE TITLE
_redirects spec

### ISSUE THREAD

**Issue by justincjohnson** [fission-codes/go-ipfs#41]
When ready, follow the steps at https://github.com/ipfs/specs/issues/257#issuecomment-1077484817 to submit the _redirects spec.

Depends on https://github.com/ipfs/go-ipfs/pull/8816.

**Comment by justincjohnson** [comment]
Spec written in https://github.com/ipfs/specs/pull/290

**Comment by walkah** [comment]
I think we can consider this shipped 🎉
